name = "Fless-reimagined-server"
author = "Kat"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "179e19b72ea377bba524ca1fac50ff897004b1bb08dcf63cbc5102f19e7aa37d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
