name = "Fless-reimagined-server"
author = "Kat"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fafe2fe829ae31ec1175e67826918418c8392e3c42f61872a5e046535826a24"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
