name = "Fless-reimagined-server"
author = "Kat"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ca7f071c2dc931cb9765432fa87edaa801366e8170f880c75a60f255893f93a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
