name = "Fless-reimagined-server"
author = "Kat"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19a782dce58c9f8b8f802040a079a5588d274934c0602f1bf609a8235d144734"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
