name = "Fless-reimagined-server"
author = "Kat"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "257d8e82727ce27f3892fd933674c08d4d559d8353a0b457c88fa8d985db4fff"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
