name = "Fless-reimagined-server"
author = "Kat"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f073704d7709d66ecd2ac657d73177b080d7468affa513e38ac9857a23010e0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
