name = "Fless-reimagined-server"
author = "Kat"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "007756bc3b9d4f9b7038101414126557ddd630ae0b15ac7b2a95bca32c6fed99"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
