name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9730a4a23f4aa45345cf4723a2faecfbf5837348b2d3812d4030bd50d869720"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
