name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a05918a0404867e21ba2a70c65f377827a2880af9e4bacf93aaaab6705f7a0c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
