name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7c6e11d135ea3016618e83ec1fccf65bc074266f210234384ccbf6c48a1ae8d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
