name = "Fless-reimagined-client"
author = "Kat"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "472e9da8f7c9ba549d8c83a16a3aa45262c324f7a4838a3db4ab7dfa41c7b994"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
