name = "Fless-reimagined-client"
author = "Kat"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ec692edab110778c4ef59babf46c6944a6faaf79aea6bab22012f6601b71872"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
