name = "Fless-reimagined-client"
author = "Kat"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42dbcd43e5dd3a8ec026e06f5c754ec5ffaf6381ec4d5958df0feef97897a87d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
