name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e0f4003f98a2bd0d860222ed02167652027b5c05a660a6d50f6712e0d31fab"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
