name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0e17550339777444a5f422cb8ed9ce27390c92faf4f87a22ea97095d20772e2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
