name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cfdc1532f2d286f9c05400a450c80975b0f2bdcd2d51f344393a3e68bafda0f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
