name = "Fless-reimagined-client"
author = "Kat"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46cfff7337c7a14684f71e625737fc17e28a34750e8b57c607a4cbbe502ef846"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
