name = "Fless-reimagined-client"
author = "Kat"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0551c6ecee16c22aba3497c345cf42cbde593304b7eccb15eb464cd8240d029"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
