name: Release on Tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v2.1.3, etc. Adjust pattern as needed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r updater.zip ./pack-client/update.ps1 ./pack-client/update.bat

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: updater.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
